package com.riccardobusetti.unibztimetable.domain.usecases

import com.riccardobusetti.unibztimetable.domain.repositories.TimetableRepository

class Next7DaysTimetableUseCase(private val timetableRepository: TimetableRepository)